packages:
  - packages/*

catalog:
  "@alloy-js/cli": 0.22.0
  "@alloy-js/core": 0.22.0
  "@alloy-js/rollup-plugin": 0.1.0
  "@alloy-js/typescript": 0.22.0
  "@typespec/compiler": 1.8.0
  "@typespec/emitter-framework": 0.15.0
  "@typespec/http": 1.8.0
  "@typespec/openapi": 1.0.0
  "@typespec/rest": 1.0.0
  typescript: 5.9.3
  vitest: 4.0.18
  eslint: 9.39.2
  prettier: 3.8.1

catalogs:
  build:
    rimraf: 6.1.2
    tsup: 8.3.5
  test:
    "@types/node": 24.10.10
    "@vitest/ui": 4.0.18
