packages:
  - "packages/*"

catalog:
  "@typespec/compiler": 1.8.0
  "@typespec/http": 1.8.0
  "@typespec/rest": 1.0.0
  "@typespec/openapi": 1.0.0
  "@alloy-js/core": 0.22.0
  "@alloy-js/typescript": 0.22.0
  typescript: 5.9.3
  vitest: 4.0.18
  eslint: 9.39.2
  prettier: 3.8.1

catalogs:
  build:
    tsup: 8.3.5
    rimraf: 6.0.1

  test:
    "@vitest/ui": 4.0.18
    "@types/node": 24.10.10
