packages:
  - 'packages/*'

catalog:
  '@typespec/compiler': ^0.63.0
  '@typespec/http': ^0.63.0
  '@typespec/rest': ^0.63.0
  '@typespec/openapi': ^0.63.0
  typescript: ^5.7.2
  vitest: ^2.1.8
  eslint: ^9.17.0
  prettier: ^3.4.2

catalogs:
  build:
    tsup: ^8.3.5
    rimraf: ^6.0.1

  test:
    '@vitest/ui': ^2.1.8
    '@types/node': ^22.10.5
